name: musicbox-mpd
summary: A web based MPD Client
description: |
  a web based MPD Client
version: 0.3.1
base: core22
confinement: strict

parts:
  musicbox-mpd:
    plugin: python
    source: .

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  musicbox-daemon:
    command: bin/musicbox-mpd
    daemon: simple
    plugs:
      - network
      - network-bind

  musicbox-mpd:
    command: bin/musicbox-mpd
    plugs:
      - network
      - network-bind

  playcounter-daemon:
    command: bin/playcounter-mpd
    daemon: simple
    plugs:
      - network

  playcounter-mpd:
    command: bin/playcounter-mpd
    plugs:
      - network
